### ISSUE TITLE
Unable to sort associated column in data table

### ISSUE THREAD

**Issue by mugilank** [mgroeneweg/mendix-DataTables#1]
@mgroeneweg : Unable to sort the field populated based on reference in data table. Try sorting the country name field populated in search filter 1 of demo project.

**Comment by mgroeneweg** [comment]
You're right! Should have found that one myself... I will look into it.

**Comment by mgroeneweg** [comment]
Fixed in next release

**Comment by mugilank** [comment]
Great :)
