### ISSUE TITLE
Can this widget enhanced to store the grid setting (column altered by user) in database?

### ISSUE THREAD

**Issue by mugilank** [mgroeneweg/mendix-DataTables#3]
Hi @mgroeneweg 

It's really good to have this widget configured to store grid settings in user specific as a cookie. Can this be stored in database and reloaded each time when user logged in.Because it adds more power to widget as well as provide flexibility for individual user to have their home page configured as one time activity.

**Comment by mgroeneweg** [comment]
The widget does not use cookies but local storage in the browser. When your users open the page again the settings should be loaded again, unless they denied access to local storage.

Storing it in the server database would probably degrade performance as the settings get saved quite often.
