### ISSUE TITLE
Adding boolean field in Datatable widget

### ISSUE THREAD

**Issue by swathiAMD** [mgroeneweg/mendix-DataTables#4]
I found the issue. I have added an Boolean as the new field in the attribute search fields. This gives me the java script error in the datatable.js attrval.toLowercase(). I modified the js as attrval.toString().toLowercase() but also it doesnt work. May be its an bug in widget?

**Comment by mgroeneweg** [comment]
Sorry for the slow response. Please check the documentation and the sample project. You should use an enumeration for a boolean search .
